version: "3"

services:
  web:
    build: .
    ports:
      - "7070:7070"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: "wordpress:latest"
