---
- name: Build WordPress environment
  hosts: all
  become: yes
  vars:
    wordpress_version: 5.6
    wordpress_db_name: wordpress
    wordpress_db_user: lucas
    wordpress_db_password: root
    wordpress_site_url: test.com
    wordpress_admin_user: lucas
    wordpress_admin_password: root
    wordpress_admin_email: admin@example.com
  tasks:
  - name: Install LAMP stack
    package:
      name: "{{ item }}"
      state: present
    with_items:
       - apache2
       - php
       - libapache2-mod-php
       - php-mysql
  - name: Create WordPress database
    mysql_db:
      name: "{{ wordpress_db_name }}"
      login_host: 192.168.6.10
      login_user: "{{ wordpress_db_user }}"
      login_password: "{{ wordpress_db_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present
  - name: Download WordPress
    get_url:
      url: https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
      dest: /tmp
  - name: Extract WordPress
    unarchive:
      src: /tmp/wordpress-{{ wordpress_version }}.tar.gz
      dest: /var/www/html/
      remote_src: yes
  - name: Configure WordPress
    template:
      src: wp-config.php
      dest: /var/www/html/wordpress/wp-config.php
    vars:
      db_name: "{{ wordpress_db_name }}"
      db_user: "{{ wordpress_db_user }}"
      db_password: "{{ wordpress_db_password }}"
  - name: Set ownership and permissions
    file:
      path: /var/www/html/wordpress
      owner: www-data
      group: www-data
      mode: "u=rwX,g=rwX,o=rX"
  - name: Install Docker
    apt:
      name: docker.io
      state: present
  - name: Install Docker Compose
    shell: |
      curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
  - name: Create Dockerfile for WordPress
    copy:
      src: Dockerfile-wordpress
      dest: /var/lib/docker/wordpress/Dockerfile
  - name: Create Dockerfile for Redis
    copy:
      src: Dockerfile-redis
      dest: /var/lib/docker/redis/Dockerfile
  - name: Configure docker-compose.yml
    copy:
      src: docker-compose.yml
      dest: /var/lib/docker/docker-compose.yml
  - name: Start WordPress and Redis containers
    command: docker-compose up -d
    args:
      chdir: /var/lib/docker/

