---
- hosts: webservers
  become: yes
  vars:
    db_name: wordpress
    db_user: lucas
    db_password: root
    wp_url: mywordpress.com
    wp_title: My WordPress Site
    wp_user: luc
    wp_password: 1234
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install packages
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - apache2
      - php
      - libapache2-mod-php
      - mysql-server
      - php-mysql
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - zip
      - unzip

  - name: Enable Apache modules
    apache2_module:
      name: "{{ item }}"
      state: present
    loop:
      - rewrite
      - headers

  - name: Create MySQL database
    mysql_db:
      name: "{{ db_name }}"
      state: present
      login_user: root
      login_password: root
      encoding: utf8

  - name: Create MySQL user
    mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_password }}"
      priv: "{{ db_name }}.*:ALL"
      login_user: root
      login_password: root

  - name: Download and extract WordPress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html
      remote_src: yes
      owner: www-data
      group: www-data

  - name: Configure WordPress
    template:
      src: wp-config.php.j2
      dest: /var/www/html/wordpress/wp-config.php
      owner: www-data
      group: www-data
      mode: '0644'

  - name: Set file permissions
    file:
      path: "{{ item }}"
      state: directory
      owner: www-data
      group: www-data
      mode: '0755'
      recurse: yes
    loop:
      - /var/www/html/wordpress/wp-content/uploads
      - /var/www/html/wordpress/wp-content/plugins
      - /var/www/html/wordpress/wp-content/themes

  - name: Restart Apache
    service:
      name: apache2
      state: restarted

