---
- name: Build and start WordPress and Redis containers
  hosts: all
  become: yes
  vars:
    wordpress_version: 5.6
    wordpress_db_name: wordpress
    wordpress_db_user: lucas
    wordpress_db_password: root
    wordpress_site_url: test.com
    wordpress_admin_user: lucas
    wordpress_admin_password: root
    wordpress_admin_email: admin@example.com
    docker_wordpress_image: wordpress:latest
    docker_redis_image: redis:latest
  tasks:
  - name: Install Docker
    apt:
      name: docker.io
      state: present
  - name: Install Docker Python module
    pip:
      name: docker
  - name: Build WordPress Docker image
  docker_image:
    name: "{{ docker_wordpress_image }}"
    build:
      path: /var/lib/docker/wordpress/
      tag: "{{ docker_wordpress_image }}"
  - name: Build Redis Docker image
    docker_image:
      name: "{{ docker_redis_image }}"
      build:
        path: /var/lib/docker/redis/
        tag: "{{ docker_redis_image }}"
  - name: Start Redis container
    docker_container:
      name: redis
      image: "{{ docker_redis_image }}"
      state: started
      restart_policy: always
  - name: Start WordPress container
    docker_container:
      name: wordpress
      image: "{{ docker_wordpress_image }}"
      state: started
      restart_policy: always
      env:
        WORDPRESS_DB_NAME: "{{ wordpress_db_name }}"
        WORDPRESS_DB_USER: "{{ wordpress_db_user }}"
        WORDPRESS_DB_PASSWORD: "{{ wordpress_db_password }}"
        WORDPRESS_DB_HOST: "mysql"
        WORDPRESS_TABLE_PREFIX: "wp_"
        WORDPRESS_AUTH_KEY: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits,punctuation') }}"
        WORDPRESS_SECURE_AUTH_KEY: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits,punctuation') }}"
        WORDPRESS_LOGGED_IN_KEY: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits,punctuation') }}"
        WORDPRESS_NONCE_KEY: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits,punctuation') }}"
        WORDPRESS_AUTH_SALT: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits,punctuation') }}"
        WORDPRESS_SECURE_AUTH_SALT: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits,punctuation') }}"
        WORDPRESS_LOGGED_IN_SALT: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits,punctuation') }}"
        WORDPRESS_NONCE_SALT: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits,punctuation') }}"
      ports:
        - "80:80"
      links:
        - redis:mysql
      volumes:
        - /var/www/html/wordpress:/var/www/html
      depends_on:
        - redis

